spring:
  application:
    name: servicediscovery
  config:
    import: optional:configserver:http://localhost:8071/

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
