spring:
  application:
    name: "servicediscovery"

server:
  port: 8761
  servlet:
    context-path: "/service-discovery"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false